# Generated by Django 3.0.4 on 2020-03-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='no_of_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='school',
            table='tbl_schools',
        ),
    ]
